name: Educational Documentation Template
about: Template for creating standardized educational documentation including talent development plans, course syllabi, and teaching schedules.
description: This template provides a structured approach to creating educational documentation with standardized formatting and linting.
icon: book
color: blue